#!/usr/bin/env node

const Koa = require('koa');
const koaBody = require('koa-body');
const static = require('koa-static');
const views = require('koa-views');
const config = require('./config/config');
const router = require('./app/router');
const errHandler = require('./app/common/errorHandler');
const open=require("open")
const app = new Koa();

app.use(views(__dirname + '/app/view', {
  extension: 'ejs'
}));

app.use(static(__dirname+'/public'));

app.use(async (ctx, next) => {
    ctx.set("Access-Control-Allow-Origin", "*");
    ctx.set('Access-Control-Allow-Credentials', true);
    ctx.set("Access-Control-Allow-Methods", "OPTIONS, GET, PUT, POST, DELETE");
    ctx.set("Access-Control-Allow-Headers", "x-requested-with,Authorization,Content-Type,Accept");

    if(ctx.method == 'OPTIONS') {
        ctx.response.status = 200;
    }
    
    await next();
});

app.use(koaBody({
    multipart:true,
    formLimit: "10mb",
    jsonLimit: "10mb",
    textLimit: "10mb",
}));


app.use(errHandler);

app.use(router.routes());



app.listen(config.port);
//自动打开页面
async function openAuto() {
    await open("http://localhost:9999/view/index");
}
openAuto()


const env = process.env.NODE_ENV?process.env.NODE_ENV:'def';
console.log('cmuser started by port ' + config.port + ' in ' + env);